packageExtensions:
  "@vue/cli-plugin-typescript@*":
    peerDependencies:
      babel-loader: "*"
  "@vue/cli-service@*":
    peerDependencies:
      "@vue/cli-plugin-babel": "*"
      "@vue/cli-plugin-eslint": "*"
      "@vue/cli-plugin-typescript": "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      vue-template-compiler: "*"
    peerDependencies:
      typescript: "*"
  vue-router@*:
    dependencies:
      vue: "*"
  vuex@*:
    dependencies:
      vue: "*"
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/checkbox@*":
    dependencies:
      framer-motion: "*"
  "@chakra-ui/transition@*":
    dependencies:
      framer-motion: "*"
  "@strapi/admin@*":
    dependencies:
      object-assign: "*"
      whatwg-fetch: "*"
      react-is: "*"
  "@strapi/babel-plugin-switch-ee-ce@*":
    dependencies:
      "@babel/template": "*"
      reselect: "*"
      resolve: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
