import type { NextPage } from 'next';
import Head from 'next/head';
import { Box, Divider, Heading, HStack, Stack, Text } from '@chakra-ui/react';
import dynamic from 'next/dynamic';

const Playground = dynamic(() => import('@/components/Playground'));

const Home: NextPage = () => {
  return (
    <Box bgColor="gray.800">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack spacing={4}>
        <Playground>
          <Stack spacing={4} alignItems="center" minW={128} w="40%">
            <Heading size="2xl">Jaden Giordano</Heading>
            <Divider bgColor="white" />
            <HStack spacing={2}>
              <Text color="yellow.300">Frontend</Text>
              <Text>&#8226;</Text>
              <Text color="teal.300">Design</Text>
              <Text>&#8226;</Text>
              <Text color="purple.300">Game Development</Text>
            </HStack>
          </Stack>
        </Playground>
      </Stack>
    </Box>
  );
};

export default Home;
